apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-nginx-rc
  labels:
    app: myapp-nginx
    type: front-end
spec:
  template:
    metadata:
      name: myapp-nginx-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: myapp-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.1"
            memory: "150Mi"
  replicas: 3