apiVersion: apps/v1
kind: ReplicSet
metadata:
  name: myapp-nginx-rs
  labels:
    app: myapp-nginx
    type: front-end
spec:
  template:
    metadata:
      name: myapp-nginx-pod
      labels:
        app: nginx-rs
        type: front-end
    spec:
      containers:
      - name: nginx-container-rs
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.1"
            memory: "150Mi"
  replicas: 3
  selector:
    matchLabels:
      type: front-end