apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10 #7 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx #1.24 1.16.1 1.14.2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80